<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [
	{
		"backMenu":[
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户表管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户表管理"
            },{
                "child":[
                    {
                        "buttons":[	
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"化妆品管理",
                        "menuJump":"列表",
                        "tableName":"huazhuangpin"
                    }
                ],
                "menu":"化妆品管理"
            },
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"工艺管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_gongyi"
                    }
                ],
                "menu":"工艺管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_leixing"
                    }
                ],
                "menu":"类型管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"品牌管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_pinpai"
                    }
                ],
                "menu":"品牌管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"配方管理",
                        "menuJump":"列表",
                        "tableName":"peifang"
                    }
                ],
                "menu":"配方管理"
            },{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"订单管理",
                        "menuJump":"列表",
                        "tableName":"dingdan"
                    }
                ],
                "menu":"订单管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
	{
		"backMenu":[
			{
                "child":[
                    {
                        "buttons":[	
                            "查看",
                            "购买"
                        ],
                        "menu":"化妆品管理",
                        "menuJump":"列表",
                        "tableName":"huazhuangpin"
                    }
                ],
                "menu":"化妆品管理"
            },
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"工艺管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_gongyi"
                    }
                ],
                "menu":"工艺管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_leixing"
                    }
                ],
                "menu":"类型管理"
            },
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"品牌管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_pinpai"
                    }
                ],
                "menu":"品牌管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"配方管理",
                        "menuJump":"列表",
                        "tableName":"peifang"
                    }
                ],
                "menu":"配方管理"
            },{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"订单管理",
                        "menuJump":"列表",
                        "tableName":"dingdan"
                    }
                ],
                "menu":"订单管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
